from module.base.button import Button
from module.base.template import Template

# This file was automatically generated by dev_tools/button_extract.py.
# Don't modify it manually.

OCR_PRE_BATTLE_CHECK = Button(area={'cn': (751, 526, 953, 569), 'en': (751, 526, 953, 569), 'jp': (751, 526, 953, 569), 'tw': (751, 526, 953, 569)}, color={'cn': (130, 137, 151), 'en': (130, 137, 151), 'jp': (130, 137, 151), 'tw': (130, 137, 151)}, button={'cn': (751, 526, 953, 569), 'en': (751, 526, 953, 569), 'jp': (751, 526, 953, 569), 'tw': (751, 526, 953, 569)}, file={'cn': './assets/cn/gg_handler/OCR_PRE_BATTLE_CHECK.png', 'en': './assets/cn/gg_handler/OCR_PRE_BATTLE_CHECK.png', 'jp': './assets/cn/gg_handler/OCR_PRE_BATTLE_CHECK.png', 'tw': './assets/cn/gg_handler/OCR_PRE_BATTLE_CHECK.png'})
